# Generated by Django 5.0.7 on 2024-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='codigo_acesso',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
