# Generated by Django 5.0.7 on 2024-12-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partida_ativa_partida_codigo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='questao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.questao'),
        ),
    ]
