# Generated by Django 5.0.7 on 2025-01-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partida_questao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='questao_atual_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
