# Generated by Django 5.0.7 on 2025-01-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_partida_questao_atual_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tempo_para_resposta',
            field=models.IntegerField(default=10),
        ),
    ]
