# Generated by Django 5.0.7 on 2025-01-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questao_tempo_para_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='jogando',
            field=models.BooleanField(default=True),
        ),
    ]
