#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


export PATH=$PATH:$HOME/.local/bin

exec python manage.py migrate

exec python manage.py seed

exec python manage.py runserver 0.0.0.0:8000
#exec daphne -b 0.0.0.0 -p 8000 config.asgi:application
#exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
