version: "3.9"
name: desafia-backend
services: 

  node:
      container_name: desafia_backend
      image: maaaure/desafia-backend
      build:
          context: ./
          dockerfile: compose/Dockerfile
      ports:
          - "8000:8000"
      networks:
          - desafia_network
  postgres:
    image: postgres
    container_name: desafia_postgres
    environment:
      POSTGRES_USER: desafia
      POSTGRES_PASSWORD: desafia-password
      POSTGRES_DB: desafiadb
    ports:
      - "5432:5432"
    networks:
      - desafia_network
  redis:
    image: redis
    container_name: desafia_redis
    ports:
      - "6379:6379"
    networks:
      - desafia_network

networks:
  desafia_network:
    driver: bridge
