version: "3.9"

services:
  postgres:
    image: postgres
    container_name: desafia_postgres
    environment:
      POSTGRES_USER: desafia
      POSTGRES_PASSWORD: desafia-password
      POSTGRES_DB: desafiadb
    ports:
      - "5432:5432"
    networks:
      - desafia_network

  redis:
    image: redis
    container_name: desafia_redis
    ports:
      - "6379:6379"
    networks:
      - desafia_network

networks:
  desafia_network:
    driver: bridge
