version: "3.9"
name: desafia-backend
services: 

  django:
    container_name: desafia_backend
    image: maaaure/desafia-backend
    build:
        context: ./
        dockerfile: compose/Dockerfile
    env_file:
        - ./.envs/.postgres
        - ./.envs/.django
    ports:
        - "8000:8000"
    networks:
        - desafia_network
    depends_on:
        - postgres
        - redis

  postgres:
    image: postgres
    container_name: desafia_postgres
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"
    networks:
      - desafia_network
  redis:
    image: redis
    container_name: desafia_redis
    ports:
      - "6379:6379"
    networks:
      - desafia_network

networks:
  desafia_network:
    driver: bridge
