name: Build and Publish image to Docker Hub
on: [workflow_dispatch]

jobs:
  deploy:
    name: Build and Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker Compose Build and Up
        run: sudo docker compose -f docker-compose.homolog.yml --env-file .envs/.homolog/.node up --build;

      - name: Docker login
        run: sudo docker login -u maaaure -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to registry
        run: sudo docker compose push maaaure/desafia-frontend:latest
